// Account singleAccount = new Account ();
// singleAccount.Name = "TEST-1 " + "FROM SNIPPET";


// Account singleAccount= new Account ();
// singleAccount.Name = 'TEST-7 ' + 'Seconf Test From Snipped';
// insert singleAccount;


Account acc= new Account ();
    acc.Name = 'TEST-9 ' + 'Account Trigger';
    acc.BillingState = 'CV';
    acc.BillingCity ='Buffalo';
    acc.BillingStreet = 'Eggert Street';
    acc.BillingPostalCode = '14225';
    acc.BillingCountry =  'USA';
insert acc;





