// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents

Duplicate example05
accept user name,title
add user id automatically
Add the member to the List


write a todo App

//  Test 
 sfdx force:lightning:lwc:test:setup